  version: '3.8'


  services:
    app:
      image: 'user-e-commerce.jar'
      build:
        context: .
        dockerfile: Dockerfile
      container_name: app
      depends_on:
        - db
      ports:
        - "8080:8080"
      networks:
        - app-network



    db:
      image: postgres:latest
      container_name: db
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=Sqlserver123@
        - POSTGRES_DB=jwt_ecommerce
      ports:
        - "5432:5432"
      networks:
        - app-network
  networks:
      app-network:
        driver: bridge
