spring:
  application:
    name: Ecommerce
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/jwt_ecommerce
    username: postgres
    password: Sqlserver123@
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        ddl-auto: update
        format_sql: true
        show-sql: true
        jdbc:
          time_zone: UTC

    database-platform: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    logging:
      level:
        org:
          springframework=DEBUG:
                  hibernate:
                    type:
                      descriptor:
                        sql:
                          BasicBinder=TRACE:

