spring:
  application:
    name: Ecommerce

  datasource:
    url: jdbc:postgresql://localhost:5432/jwt_ecommerce
    username: postgres

    password: Johns@1995

    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

  data:
    mongodb:
      uri: mongodb://localhost:27017/pincode

  # Uncomment if you need to allow bean definition overriding
  # main:
  #   allow-bean-definition-overriding: true

  database-platform: org.hibernate.dialect.PostgreSQLDialect

razorpay:
  key: rzp_test_cWF3MY4jPZmK8Z
  secret: gW79NCDroicKdyDE7RhEl9g4v

twilio:
  accountSid:
  authToken:
  whatsappNumber:
  phoneNumber:

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Uncomment to configure logging levels
# logging:
#   level:
#     org.springframework: DEBUG
#     root: DEBUG
