spring:
  application:
    name: Ecommerce
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/jwt_ecommerce
    username: postgres
    password: Johns@1995
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG